import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const googleSansCode = localFont({
    src: [
        {
            path: "../public/fonts/Google_Sans_Code,Karla,Merriweather/Google_Sans_Code/static/GoogleSansCode-SemiBold.ttf",
            weight: "600",
            style: "normal",
        },
    ],
    variable: "--font-google-sans-code",
    display: "swap",
});

export const metadata = {
    title: "Portable Gallery",
    description: "Generated by NextJS",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${googleSansCode.variable} ${googleSansCode.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
